- name: Deployen von VanVentura mit Docker
  hosts: all
  become: true
  collections:
    - community.docker

  vars:
    # Definieren Sie den Hash (z. B. GitHub-SHA). Dies sollte dynamisch gesetzt werden.
    docker_image_tag: "{{ lookup('env', 'GITHUB_SHA') | default('latest') }}"
    docker_image_name: 'klatschenderaffe/vanventura'
    docker_image_name_backend: 'klatschenderaffe/vanventura_backend'

  tasks:
    # IN DEN USERDATA
    # - name: System aktualisieren
    #   package:
    #     name: '*'
    #     state: latest
    #   become: true
    # # 2. Docker installieren
    # - name: Docker aus Standard-Repositories installieren
    #   apt:
    #     name: docker.io
    #     state: present
    #     update_cache: true
    #   become: true
    # 3. Docker starten und aktivieren
    - name: Docker starten und aktivieren
      systemd:
        name: docker
        state: started
        enabled: true

    # ################ BACKEND #############################################
    - name: Docker Image pullen
      community.docker.docker_image:
        name: '{{ docker_image_name_backend }}'
        tag: '{{ docker_image_tag }}'
        source: pull

    # 5. Docker Container starten mit spezifischem Tag (Hash)
    - name: Docker Container starten
      community.docker.docker_container:
        name: vanventura-backend-container
        image: '{{ docker_image_name_backend }}:{{ docker_image_tag }}'
        state: started
        restart_policy: always
        published_ports:
          - '5000:5000' # Ändern Sie den Host-Port von 80 auf einen freien Port wie 8080

    # ############### FRONTEND #################################
    - name: Docker Image pullen
      community.docker.docker_image:
        name: '{{ docker_image_name }}'
        tag: '{{ docker_image_tag }}'
        source: pull

    # 5. Docker Container starten mit spezifischem Tag (Hash)
    - name: Docker Container starten
      community.docker.docker_container:
        name: vanventura-container
        image: '{{ docker_image_name }}:{{ docker_image_tag }}'
        state: started
        restart_policy: always
        published_ports:
          - '80:80' # Ändern Sie den Host-Port von 80 auf einen freien Port wie 8080

