# Ziel diese Workflows ist es die Anwendung zu testen und
# ein Image bauen zu lassen. Anschließen wird das Image auf Dockerhub gepushed.
name: Image erstellen und pushen
on:
  # Wird mit einem Push auf den Branch "Main" ausgelöst.
  push:
    branches:
      - main
jobs:
  # Die Anwendung wird getestet.
  test:
    runs-on: ubuntu-latest
    steps:
      # Code auschecken
      - name: Check out code
        uses: actions/checkout@v4
        # Node aktualisieren
      - name: Node aktualisieren
        uses: actions/setup-node@v4
        with:
          node-version: 22
        # Alle Abhängigkeiten installieren
      - name: Abhängigkeiten installieren
        run: npm install
        # React Tests ausführen
      - name: React Test ausführung
        run: npm run test

  # Das Image wird auf Dockerhub gepushed
  image_push:
    runs-on: ubuntu-latest
    # Hat die Abhängigkeit von dem "test" Job,
    # erst wenn dieser erfolgreich durchlief darf dieser Workflow starten.
    needs: test
    steps:
      # build job soll den build ordner als artefakt hochladen
      # schritt 1: code auschecken
      - name: Check out code
        uses: actions/checkout@v4
      # schritt 2: node aktualisieren
      - name: Node aktualisieren
        uses: actions/setup-node@v4
        with:
          node-version: 22
        # Zur Kontrolle
      - name: Dateipfade anzeigen lassen
        run: ls -la
      # schritt 3: Abhängigkeiten installieren
      - name: Abhängigkeiten installieren
        run: npm install
      # Schritt 3: Projekt-Build bauen und Image erstellen
      - name: Docker Image erstellen und taggen
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/vanventura
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build \
            --tag $IMAGE_NAME:$IMAGE_TAG \
            --tag $IMAGE_NAME:latest \
            .
      # Step 2: Einloggen in Dockerhub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Schritt 5: Docker Image pushen
      - name: Docker Image pushen
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/vanventura
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
